---
# tasks file for aap_requirements_check
- name: Configure database firewall rules
  when:
    - '"database" in groups'
    - inventory_hostname in groups['database']
  ansible.posix.firewalld:
    port: "{{ ports }}/tcp"
    permanent: yes
    immediate: true
    state: enabled
  loop:
    - "{{ ansible_port }}"
    - "{{ pg_port }}"
  loop_control:
    loop_var: ports
    